/*-------------------------------------------------------------------
|                    🚀 NEXTJS POLYGLOT APP 🚀
|
|  HELLO 👋! WELCOME TO POLYGLOT APP. THIS APP FETCHES DATA FROM AN 
|  EXTERNAL API AND DISPLAYS THE DATA. THIS APP FOR lEARNING 
|  LANGUAGES THROUGH QUICK, BITE-SIZED LESSONS. PRACTICE SPEAKING.
|  READING, LISTENING, AND WRITING TO BUILD YOUR VOCABULARY AND
|  GRAMMAR SKILLS, FEEL FREE TO REACH OUT TO ME OR OPEN AN ISSUE 
|  ON GITHUB. THANKS!
|
|  🔗CREATOR: https://github.com/zehan12
|  🔗SOURCE CODE: https://github.com/zehan12/polyglot
|
*-------------------------------------------------------------------*/
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Nunito } from "next/font/google";
import "./globals.css";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
